### ISSUE TITLE
extracting (not issue)

### ISSUE THREAD

**Issue by EVRICA** [proj3rd/asn3rd#2]
Hi!
Could you explain how asn3rd cli works?
To be more precise - what input file type is? pdf? or something else?
And output file format would be *.asn?

**Comment by gsongsong** [comment]
asn3rd extractor CLI takes an original 3GPP standard specification file (a file extension with `.doc` or `.docx`). Also it takes a plain text file (with the other file extensions) converted from the abovementioned file.

**Comment by EVRICA** [comment]
Thank you!
